{% set version = "1.3.2" %}

package:
  name: pynfft
  version: {{ version }}

source:
  fn: pyNFFT-{{ version }}.tar.bz2
  url: https://pypi.io/packages/source/p/pyNFFT/pyNFFT-{{ version }}.tar.gz
  md5: d2457a3f43839a8acce3295c60d5e692

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - python
    - pip
    - numpy 1.8.*   # [not (win and (py35 or py36))]
    - numpy 1.9.*   # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - nfft >=3.2,<3.3
    - gcc
    - cython
  run:
    - python
    - numpy >=1.8   # [not (win and (py35 or py36))]
    - numpy >=1.9   # [win and py35]
    - numpy >=1.11  # [win and py36]
    - nfft >=3.2,<3.3
    - libgcc

test:
  imports:
    - pynfft
  commands:
    - python -c "from pynfft.nfft import NFFT; plan = NFFT(8, 8)"

about:
  home: https://github.com/ghisvail/pyNFFT.git
  license: GPLv3
  summary: Pythonic bindings around the NFFT library

extra:
    recipe-maintainers:
      - ghisvail
      - grlee77
