travis:
  secure:
    BINSTAR_TOKEN: KwNg+pbICJyqXJ+bI/Y+NtluKxa5EbfUUixEdZgHArM8TCmT5S/inOkbV+s4C9SHFe51exKlPR2IM53GK1bVdQln0LMsmys8dCMnawTrtcEUkrxCpTIua2IA7Nu8fewgrhfQse9DO5IQscIAj8bsFZblXupDuqW3WcuyPBDyFGDI5PNm2Lxh7832vvhUg00LrGU2H9JNDjWA47/++1c1hLX4KGMrtcI6tUJJvXGDDM11b0dw1xFX53Za9lWtTRg4/KMNSuzmwHVksuFJBcRKh6UA82M5PKOQE9ZJw76reXk1t7rLfKYyDyq+Pe3ZXcImQ3q9V449En7+4MI+D3c4IGaB8JYOunCOhy8C8PHuV0hJQfUO7nEQjes2HDGY9YId9Ln9kcDFxo8iOY7Ffmw7lzpyHqEFMr0ghF4IWtBYlSk19q4BwbMYGp1QJXDZgLRNa2wL6JXIfZcKpFjQZbrTZNUthck5PWQMMRKy4MNra8Pp1Hcc1voIr1CQo9NcdgJRllzEUYPgk2ZNXwhAu3GCXsGMrnE0Ui/iQ7LncYx1g3d/0YlTu0KEETskg+drFRS9VCcTiDPq5NkghPzP5gwDzAgAFiNFWCQD9bquVffT8nBnHePHfUBagOeGWA3KR6LIjzFtb45c4NcXtd31JKE1QZYwIZOWbailORQrCqcBL0M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
